package com.application.studyroom.utils

const val RESULT_OK_JOIN_ROOM = 101
const val RESULT_NOT_OK_JOIN_ROOM = 102
const val RESULT_OK_CREATE_ROOM = 201
const val RESULT_NOT_OK_CREATE_ROOM = 202
const val RESULT_OK_CREATE_ANNOUNCEMENT = 301
const val RESULT_NOT_OK_CREATE_ANNOUNCEMENT = 302
